name: reusable_with_outputs

on:
  workflow_dispatch:
    # You cannot define outputs from a manually triggered workflow
    
  workflow_call:
    outputs:
      myOutput:
        description: Output from resuable workflow
        # Map the Workflow outputs to Job Outputs
        value: ${{ jobs.Get_Value.outputs.outputValue }}
        
      mySensitiveOutput:
        description: Output from a reusable workflow that is considered sensitive
        value: ${{ jobs.Get_Value.outputs.sensitiveOutputValue }}

jobs:

  Get_Value:
    name: Generate an Output Value
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      outputValue: ${{ steps.step1.outputs.outputVal }}
      sensitiveOutputValue: ${{ steps.step2.outputs.outputVal }}

    steps:
      - id: step1
        run: echo "outputVal=Hello. I am a string curated within a reusable workflow." >> $GITHUB_OUTPUT

      - id: step2
        run: |
          secret=A${RANDOM}B${RANDOM}C${RANDOM}
          echo "::add-mask::$secret"       # Mask the secret in logs
          echo "The secret is:" $secret    # Added this to prove the masking works
          echo "outputVal=$secret" >> $GITHUB_ENV

      - run: echo "::set-output name=outputVal::$secret"
