name: reusable_with_secret_inputs

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      MY_SECRET:
        description: 'A value passed in from a GitHub Secret'
        required: true

jobs:
  Print-Secret:
    runs-on: ubuntu-latest
    env:
      # The Secret has been put into an EnvVar because this sanitised any special characters.
      # which would otherwise cause the shell commands to error when the secret value is accessed
      env_secretValue: ${{ secrets.MY_SECRET }}
      
    steps:
      # This will be output to the log with obfuscation
      - run: echo "My obfuscated secret value is:" $env_secretValue

      # But remember that it's circumventable
      - run: |
          # secretValue="${{ secrets.MY_SECRET }}"
          echo "My compromised secret value is:"
          echo "(pt1):" ${env_secretValue:0:2}
          echo "(pt2):" ${env_secretValue:2:30}
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # Doing this would reveal that it contains the Secret. Though in the logs it will be obfuscated.
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"
          
  Dump-Context-Invoked-From-Reusable-WF:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      # Env vars not printed from this job since the secret env-var was scoped to the first job
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"
