name: reusable_with_inputs

on:
  workflow_dispatch:
    inputs:
      firstName:
        type: string
        required: false
        default: "Mr/Mrs"
      lastName: 
        type: string
        required: true
  workflow_call:
    inputs:
      firstName:
        type: string
        required: false
        default: "Mr/Mrs"
      lastName: 
        type: string
        required: true

jobs:
  Print-Name:
    runs-on: ubuntu-latest

    steps:
      # Don't do the following. It is vulnerable to script injection via the inputs
      # - run: echo ${{ inputs.firstName }} ${{ inputs.lastName }}
