name: reusable_with_inputs

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      MY_SECRET:
        description: 'A value passed in from a GitHub Secret'
        required: true
      

jobs:
  Print-Secret:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello ${{ secrets.MY_SECRET }}
