name: Call Privileged Workflow

on:
  workflow_call:
    secrets:
      IMAGE_REGISTRY_WRITE_KEY:
        required: false

jobs:
  
  middleman_job:
    uses: MarkTopping/gha-reusable-wf-with-oidc/.github/workflows/demo-privileged-upload-image.yml@main
    secrets: 
      # IMAGE_REGISTRY_WRITE_KEY: ${{ secrets.IMAGE_REGISTRY_WRITE_KEY }}
      IMAGE_REGISTRY_WRITE_KEY: test
      
        
